apiVersion: "networking.istio.io/v1beta1"
kind: "Gateway"
metadata:
  name: "ingressgateway"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  selector:
    istio: "ingressgateway"
  servers:
    # This port is reserved for the webclient. For more information see the
    # following files.
    #
    #     kia/env/knd/istio.yaml
    #     kia/env/knd/kind.yaml
    #
    - port:
        name: "webclient"
        number: 30003
        protocol: "HTTP"
      hosts:
        - "*"

    # This port is reserved for the apiserver. For more information see the
    # following files.
    #
    #     kia/env/knd/istio.yaml
    #     kia/env/knd/kind.yaml
    #
    - port:
        name: "apiserver"
        number: 30007
        protocol: "GRPC"
      hosts:
        - "*"

    # This port is reserved for prometheus. For more information see the
    # following files.
    #
    #     kia/env/knd/istio.yaml
    #     kia/env/knd/kind.yaml
    #
    - port:
        name: "prometheus"
        number: 30009
        protocol: "HTTP"
      hosts:
        - "*"

    # This port is reserved for grafana. For more information see the following
    # files.
    #
    #     kia/env/knd/istio.yaml
    #     kia/env/knd/kind.yaml
    #
    - port:
        name: "grafana"
        number: 30030
        protocol: "HTTP"
      hosts:
        - "*"
