apiVersion: "networking.istio.io/v1beta1"
kind: "Gateway"
metadata:
  name: "ingressgateway"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  selector:
    istio: "ingressgateway"
  servers:
    - port:
        name: "https"
        number: 443
        protocol: "HTTPS"
      hosts:
        # In a remote setup using eks the istio ingress gateway forwards traffic
        # based on wildcard expressions of a hosted zone. This allows virtual
        # services to specific subdomains of their micro services according to
        # the cluster name and DNS zone.
        #
        #     *.kia02.aws.example.com
        #
        - "*.{{ .Values.cluster.name }}.{{ .Values.cluster.zone }}"
        {{- if .Values.dns.cname }}
        # In a remote setup using eks we can forward traffic based on a pretty
        # shortcut domain, if any.
        #
        #     app.example.com
        #
        - "{{ .Values.dns.cname }}"
        {{- end }}
      tls:
        mode: "SIMPLE"
        credentialName: "ingressgateway"
        minProtocolVersion: "TLSV1_2"
